-- Database creation
create database order_db;

-- Schema creation
create schema ORDER__BASE;  -- For Table creation
create schema ORDER__XFRM;  -- For Transformation logic
create schema ORDER__ANALYSIS;  -- For End user's final view

-- Table creation
-- Table creation script for table T_PROMOTION
CREATE TABLE IF NOT EXISTS ORDER__BASE.T_PROMOTION(
    PROMOTION_ID VARCHAR(10) PRIMARY KEY ,
    CUSTOMER_CATEGORY VARCHAR(10),
    PROMOTION_TYPE VARCHAR(10),
    PROMOTION_VALUE	NUMBER(10,2),
    COMMENT	VARCHAR(20)
)

-- Table creation script for table T_CUSTOMER
CREATE TABLE IF NOT EXISTS ORDER__BASE.T_CUSTOMER(
    CUSTOMER_ID	VARCHAR(10) PRIMARY KEY,
    ADDRESS	VARCHAR(50),
    PHONE_NO VARCHAR(10),
    CATEGORY VARCHAR(10),
    STATUS VARCHAR(10),
    TOTAL_ORDERS INTEGER,
    TOTAL_INVOICE_AMOUNT NUMBER(12,2),
    LOYALTY_POINTS NUMBER(12,2),
    CREATE_DATE	DATE,
    CREATE_USER	VARCHAR(30)
)

-- Table creation script for table T_ORDER_DETAIL
CREATE TABLE IF NOT EXISTS ORDER__BASE.T_SALES_ORDER_DETAIL(
    ORDER_ID VARCHAR(10) PRIMARY KEY,
    ORDER_DATE DATE,
    CUSTOMER_ID	VARCHAR(10),
    ITEM_ID	VARCHAR(10),
    QTY	INTEGER,
    TOTAL_AMOUNT NUMBER(12,2),
    CREATE_DATE DATE,
    CREATE_USER	VARCHAR(30),
    PRICE NUMBER(12,2)
)

-- Table creation script for table T_ORDER_HEADER
CREATE TABLE IF NOT EXISTS ORDER__BASE.T_SALES_ORDER_HEADER(
    ORDER_ID VARCHAR(10),
    ORDER_DATE DATE,
    STATUS VARCHAR(10),
    CUSTOMER_ID	VARCHAR(10),
    ITEM_COUNT INTEGER,
    TOTAL_AMOUNT NUMBER(12,2),
    DISCOUNT NUMBER(10,2),
    CREATE_DATE	DATE,
    CREATE_USER	VARCHAR(30),
    COUPON_CODE	VARCHAR(10)
)

-- Table creation script for table T_ORDER_HEADER
CREATE TABLE IF NOT EXISTS ORDER__BASE.T_INVOICE(
    ORDER_ID VARCHAR(10),
    ORDER_DATE DATE,
    INVOICE_DATE DATE,
    TAX_AMOUNT NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(12,2),
    DISCOUNT NUMBER(10,2),
    FINAL_INVOICE_AMT NUMBER(12,2),
    CUSTOMER_ID	VARCHAR(10),
    CREATE_DATE DATE,
    CREATE_USER	VARCHAR(30)
)

